eef_link = "centered_fixture" # the existing link in the robot URDF where KineCal attaches the calibration probe
# probe_link = "smr_ball_link"
# probe_link = "prod_ball_link"
probe_link = "trossen_calibration_link"


recording_method = "keyboard"
#recording_method = "flange_button"

[tcp_config]
policy = "cones"
cones = [
  { angle_deg = 5.0, count = 4 },
  { angle_deg = 20.0, count = 8 },
  { angle_deg = 25.0, count = 8 },
  { angle_deg = 35.0, count = 8 },
  { angle_deg = 45.0, count = 8 },
]

[outlier_detection]
enabled = true
metric = "mahalanobis"
