<?xml version="1.0"?>
<package format="3">
  <name>standard_bots_shaper_example</name>
  <version>0.1.0</version>
  <description>Hardware-free Standard Bots Reforge Shaper example.</description>
  <maintainer email="info@reforgerobotics.com">Reforge Robotics</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>trajectory_msgs</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
