"""Demonstrate Covalent KineCal configuration and trajectory compensation."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from reforge_core.control.kinecal.compensation import (
    compensate_configuration,
    compensate_trajectory,
    resolve_compensation_selection,
)
from robot.example_usage.kinecal.example_utility import (
    create_joint_limits_from_urdf,
    plan_nominal_joint_trajectory,
    plot_kinecal_example_results,
    print_compensation_selection,
    print_terminal_pose_validation,
    selected_calibrated_urdf_path,
    validate_terminal_common_link_pose,
)


THIS_DIR = Path(__file__).resolve().parent

# This is a baseline (uncalibrated) URDF of the uf850.urdf, but with
# a custom tool attached at the flange which was not necessarily
# present in the URDF used for calibration.
BASELINE_URDF_PATH = THIS_DIR / "uf850_custom_tool.urdf"
# Results generated by KineCal Identification.
KINECAL_RESULTS_DIRECTORY = THIS_DIR / "example_results"

NUM_JOINTS = 6
SAMPLE_TIME_S = 0.02
TRAJECTORY_SAMPLE_COUNT = 201
MAX_JOINT_SPEED_RAD_S = 1.5
MAX_JOINT_ACCELERATION_RAD_S2 = 3.0


def parse_cli_args() -> argparse.Namespace:
    """Parse optional reporting flags for the KineCal example script.

    Returns:
        `argparse.Namespace` parsed flags controlling optional plot output.
    Raises:
        SystemExit: If CLI parsing fails.
    """

    parser = argparse.ArgumentParser(
        description="Run the Covalent KineCal control example usage script."
    )
    parser.add_argument(
        "--skip-plot",
        action="store_true",
        help="Skip the nominal-vs-compensated trajectory plot.",
    )
    return parser.parse_args()


def main(*, show_plots: bool = True) -> None:
    """Run configuration-level and trajectory-level KineCal examples.

    Raises:
        FileNotFoundError: If the example URDF or KineCal result bundle is missing.
        ValueError: If trajectory, limit, or KineCal selection inputs are invalid.
        RuntimeError: If trajectory optimization fails.
    """

    limits = create_joint_limits_from_urdf(
        baseline_urdf_path=BASELINE_URDF_PATH,
        max_joint_speed_rad_s=MAX_JOINT_SPEED_RAD_S,
        max_joint_acceleration_rad_s2=MAX_JOINT_ACCELERATION_RAD_S2,
    )

    # Define start and goal configurations
    start_position_rad = np.array([0.0, -0.6, -1.0, 0.0, 0.5, 0.0], dtype=float)
    goal_position_rad = np.array(
        [0.3, -0.9, -1.2, 0.2, 0.7, -0.1],
        dtype=float,
    )

    # SIMULATION ONLY: this helper creates a smooth nominal trajectory so the
    # example can run without a robot SDK. In your application, replace this
    # block with the trajectory from your planner, teach pendant, or robot SDK.
    reference_trajectory, reference_report = plan_nominal_joint_trajectory(
        start_position_rad=start_position_rad,
        goal_position_rad=goal_position_rad,
        limits=limits,
        sample_count=TRAJECTORY_SAMPLE_COUNT,
        sample_time_s=SAMPLE_TIME_S,
    )
    print("\n[Reference Trajectory]")
    print(f"status={reference_report.status}")
    print(f"solve_time_s={reference_report.solve_time_s:.6f}")
    print(f"all_constraints_satisfied={reference_report.all_constraints_satisfied}")
    print(
        "terminal_position_rad="
        f"{np.array2string(reference_trajectory.positions[-1], precision=6)}"
    )

    # =========================================================================
    # Start Example 1: Compensate one terminal configuration with KineCal.
    #
    # CONTROLLER CODE TO COPY: use this pattern when your application plans or
    # commands one target joint configuration at a time.
    # =========================================================================
    compensated_goal_position_rad, configuration_selection = compensate_configuration(
        q_nom=goal_position_rad,
        baseline_urdf_path=BASELINE_URDF_PATH,
        kinecal_model_root=KINECAL_RESULTS_DIRECTORY,
    )
    # REPLACE WITH YOUR ROBOT SDK: send `compensated_goal_position_rad` as the
    # final target when your SDK accepts a single joint-space target.
    # =========================================================================
    # End Example 1.
    # =========================================================================

    print_compensation_selection(
        selection_info=configuration_selection,
        label="Configuration Compensation",
    )
    print(
        "nominal_goal_position_rad="
        f"{np.array2string(goal_position_rad, precision=6)}"
    )
    print(
        "compensated_goal_position_rad="
        f"{np.array2string(compensated_goal_position_rad, precision=6)}"
    )

    # =========================================================================
    # Start Example 2: Compensate a complete joint trajectory with KineCal.
    #
    # CONTROLLER CODE TO COPY: use this pattern when a complete nominal
    # trajectory is available before execution starts.
    # =========================================================================
    compensated_trajectory, trajectory_selection = compensate_trajectory(
        trajectory=reference_trajectory,
        limits=limits,
        baseline_urdf_path=BASELINE_URDF_PATH,
        kinecal_model_root=KINECAL_RESULTS_DIRECTORY,
    )
    # REPLACE WITH YOUR ROBOT SDK: send `compensated_trajectory.positions`,
    # `compensated_trajectory.velocities`, and
    # `compensated_trajectory.accelerations` if your SDK accepts full trajectory
    # uploads.
    # =========================================================================
    # End Example 2.
    # =========================================================================

    print_compensation_selection(
        selection_info=trajectory_selection,
        label="Trajectory Compensation",
    )
    print(
        "compensated_terminal_position_rad="
        f"{np.array2string(compensated_trajectory.positions[-1], precision=6)}"
    )

    # [Optional] Pull the specific calibrated URDF selected for compensation and
    # validate that it matches the compensated trajectory.
    selected_urdf_path = selected_calibrated_urdf_path(trajectory_selection)
    if selected_urdf_path is not None:
        validation = validate_terminal_common_link_pose(
            baseline_urdf_path=BASELINE_URDF_PATH,
            calibrated_urdf_path=selected_urdf_path,
            nominal_terminal_position_rad=reference_trajectory.positions[-1],
            compensated_terminal_position_rad=compensated_trajectory.positions[-1],
        )
        print_terminal_pose_validation(validation)

    # =========================================================================
    # Start Example 3: Inspect KineCal model selection without compensating.
    #
    # DIAGNOSTIC CODE: this call is optional. The compensation calls above
    # perform the same selection internally before deciding whether to use a
    # calibrated URDF or fall back to the baseline URDF.
    # =========================================================================
    selection_preview = resolve_compensation_selection(
        q_nom=goal_position_rad,
        baseline_urdf_path=BASELINE_URDF_PATH,
        kinecal_model_root=KINECAL_RESULTS_DIRECTORY,
    )
    # =========================================================================
    # End Example 3.
    # =========================================================================

    print_compensation_selection(
        selection_info=selection_preview,
        label="Selection Preview",
    )

    if show_plots:
        plot_kinecal_example_results(
            reference_trajectory=reference_trajectory,
            compensated_trajectory=compensated_trajectory,
            limits=limits,
        )


if __name__ == "__main__":
    main(show_plots=not parse_cli_args().skip_plot)
